"""add categories table

Revision ID: 8a2ac2600658
Revises: 120b1a127ece
Create Date: 2023-07-04 14:45:20.963610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2ac2600658'
down_revision = '120b1a127ece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
